[
  {
    pictureUrl: "https://example.com/toy1.jpg",
    name: "Avengers Action Figure 1",
    sellerName: "Johns Toys",
    sellerEmail: "john@example.com",
    subCategory: "Avengers",
    price: 19.99,
    rating: 4.5,
    availableQuantity: 10,
    description: "This action figure is based on the Avengers characters.",
  },
  {
    pictureUrl: "https://example.com/toy2.jpg",
    name: "Avengers Action Figure 2",
    sellerName: "Sarahs Collectibles",
    sellerEmail: "sarah@example.com",
    subCategory: "Avengers",
    price: 24.99,
    rating: 4.2,
    availableQuantity: 5,
    description:
      "An action figure from the Avengers series, perfect for fans of the movies.",
  },
  {
    pictureUrl: "https://example.com/toy2.jpg",
    name: "Avengers Action Figure 3",
    sellerName: "Marvel Collectibles",
    sellerEmail: "marvel@example.com",
    subCategory: "Avengers",
    price: 21.99,
    rating: 4.3,
    availableQuantity: 11,
    description:
      "An action figure from the Avengers series, perfect for fans of the movies.",
  },

  {
    pictureUrl: "https://example.com/toy3.jpg",
    name: "Transformers Action Figure 1",
    sellerName: "Maxs Toys",
    sellerEmail: "max@example.com",
    subCategory: "Transformers",
    price: 29.99,
    rating: 4.7,
    availableQuantity: 8,
    description:
      "A cool Transformers action figure that transforms into a vehicle.",
  },
  {
    pictureUrl: "https://example.com/toy4.jpg",
    name: "Transformers Action Figure 2",
    sellerName: "RoboToys",
    sellerEmail: "info@robotoys.com",
    subCategory: "Transformers",
    price: 34.99,
    rating: 4.0,
    availableQuantity: 12,
    description:
      "An epic Transformers action figure with intricate details and articulation.",
  },
  {
    pictureUrl: "https://example.com/toy4.jpg",
    name: "Transformers Action Figure 3",
    sellerName: "Matrix Toys",
    sellerEmail: "info@matrixtoys.com",
    subCategory: "Transformers",
    price: 31.45,
    rating: 4.0,
    availableQuantity: 18,
    description:
      "An epic Transformers action figure with intricate details and articulation.",
  },

  {
    pictureUrl: "https://example.com/toy5.jpg",
    name: "Star Wars Action Figure 1",
    sellerName: "Galaxy Collectibles",
    sellerEmail: "sales@galaxycollectibles.com",
    subCategory: "Star Wars",
    price: 14.99,
    rating: 4.3,
    availableQuantity: 7,
    description: "An iconic Star Wars action figure from the original trilogy.",
  },
  {
    pictureUrl: "https://example.com/toy6.jpg",
    name: "Star Wars Action Figure 2",
    sellerName: "Jedi Toys",
    sellerEmail: "info@jeditoys.com",
    subCategory: "Star Wars",
    price: 17.99,
    rating: 4.6,
    availableQuantity: 3,
    description:
      "A highly detailed Star Wars action figure based on the latest movie.",
  },
  {
    pictureUrl: "https://example.com/toy6.jpg",
    name: "Star Wars Action Figure 3",
    sellerName: "Raw Formats",
    sellerEmail: "info@rawformat.com",
    subCategory: "Star Wars",
    price: 20.99,
    rating: 4.2,
    availableQuantity: 6,
    description:
      "A highly detailed Star Wars action figure based on the latest movie.",
  },
];
